import { PROTOCOL_VERSION } from './constants';
import * as crypto from 'crypto';

export const PROTOCOL_VERSION_V1 = PROTOCOL_VERSION;

export type ProtocolVersion = typeof PROTOCOL_VERSION;

export type Role = 'admin' | 'developer' | 'data_reader' | 'viewer';

export type MessageType =
  | 'ping'
  | 'introspect'
  | 'query'
  | 'stream_query'
  | 'migration_run'
  | 'cancel'
  | 'response'
  | 'error'
  | 'stream_chunk'
  | 'stream_end'
  | 'event';

export type EventKind =
  | 'status_change'
  | 'migration_progress'
  | 'approval_required'
  | 'approval_response'
  | 'warning'
  | 'resume_request'
  | 'plan_register';

export type MigrationStatementStatus = 'pending' | 'running' | 'success' | 'failed' | 'rolled_back';

/**
 * Single envelope format for every message between browser <-> cloud <-> agent.
 * Every WebSocket frame contains exactly one AgentMessage serialized as UTF-8 JSON.
 */
export interface AgentMessage<T = unknown> {
  /** Protocol version. Must equal 1. */
  v: ProtocolVersion;

  /** UUID v4. Generated by sender. Used for request/response correlation + cancellation. */
  id: string;

  /** Message type. Determines payload shape. */
  type: MessageType;

  /** Project name. Must match a project_name in databases.config.json. */
  project: string;

  /** Acting user. Comes from browser session, never trusted blindly — agent verifies via cloud. */
  user: {
    id: string;
    role: Role;
  };

  /** DB alias. Must match a db_alias in databases.config.json. */
  db_alias: string;

  /** Epoch milliseconds. Sender's clock. Used for audit + ordering. */
  ts: number;

  /** Type-specific payload. See messages.ts. */
  payload: T;
}

/**
 * Helper: create a message with sensible defaults.
 * Useful for tests and for agent's own message construction.
 */
export function createMessage<T>(
  type: MessageType,
  opts: {
    id?: string;
    project: string;
    user: { id: string; role: Role };
    db_alias: string;
    payload: T;
  },
): AgentMessage<T> {
  const validRoles: Role[] = ['admin', 'developer', 'data_reader', 'viewer'];
  if (!validRoles.includes(opts.user.role)) {
    throw new Error(`Invalid role: ${opts.user.role}`);
  }
  return {
    v: PROTOCOL_VERSION,
    id: opts.id || crypto.randomUUID(),
    type,
    project: opts.project,
    user: opts.user,
    db_alias: opts.db_alias,
    ts: Date.now(),
    payload: opts.payload,
  };
}
